# Generated by Django 2.2.2 on 2019-06-14 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('risk_score', models.IntegerField()),
                ('summary', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('vuln_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
