# Generated by Django 2.2.2 on 2019-06-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuln',
            old_name='vuln_user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='vuln',
            name='risk_score',
            field=models.IntegerField(default=1),
        ),
    ]
