# Generated by Django 2.2.2 on 2019-06-15 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vulns', '0002_auto_20190615_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remediation', models.TextField()),
                ('status', models.CharField(max_length=60)),
                ('patches', models.CharField(max_length=200)),
                ('approved_remedy', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rems', to='vulns.Vuln')),
            ],
        ),
    ]
