# Generated by Django 2.2.2 on 2019-07-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0003_remedy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedy',
            name='status',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
