# Generated by Django 2.2.2 on 2019-06-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webroot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
